/* 
 * Copyright 2014 Key Bridge Global LLC.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package us.gov.dod.standard.ssrf._1_2_4.metadata.lists;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
import us.gov.dod.standard.ssrf._1_2_4.shared.Title;

/**
 * Enumerated values for fields using the ListLN type.
 * <p>
 * Used in {@link Title}
 * <p>
 * @author Jesse Caulfield
 * @version SSRF 1.2.4b, 11/12/2014
 */
@XmlType(name = "ListLN")
@XmlEnum
public enum ListLN {

  @XmlEnumValue("aa")
  AA("aa"),
  @XmlEnumValue("ab")
  AB("ab"),
  @XmlEnumValue("ae")
  AE("ae"),
  @XmlEnumValue("af")
  AF("af"),
  @XmlEnumValue("ak")
  AK("ak"),
  @XmlEnumValue("am")
  AM("am"),
  @XmlEnumValue("an")
  AN("an"),
  @XmlEnumValue("ar")
  AR("ar"),
  @XmlEnumValue("as")
  AS("as"),
  @XmlEnumValue("av")
  AV("av"),
  @XmlEnumValue("ay")
  AY("ay"),
  @XmlEnumValue("az")
  AZ("az"),
  @XmlEnumValue("ba")
  BA("ba"),
  @XmlEnumValue("be")
  BE("be"),
  @XmlEnumValue("bg")
  BG("bg"),
  @XmlEnumValue("bh")
  BH("bh"),
  @XmlEnumValue("bi")
  BI("bi"),
  @XmlEnumValue("bm")
  BM("bm"),
  @XmlEnumValue("bn")
  BN("bn"),
  @XmlEnumValue("bo")
  BO("bo"),
  @XmlEnumValue("br")
  BR("br"),
  @XmlEnumValue("bs")
  BS("bs"),
  @XmlEnumValue("ca")
  CA("ca"),
  @XmlEnumValue("ce")
  CE("ce"),
  @XmlEnumValue("ch")
  CH("ch"),
  @XmlEnumValue("co")
  CO("co"),
  @XmlEnumValue("cr")
  CR("cr"),
  @XmlEnumValue("cs")
  CS("cs"),
  @XmlEnumValue("cu")
  CU("cu"),
  @XmlEnumValue("cv")
  CV("cv"),
  @XmlEnumValue("cy")
  CY("cy"),
  @XmlEnumValue("da")
  DA("da"),
  @XmlEnumValue("de")
  DE("de"),
  @XmlEnumValue("dv")
  DV("dv"),
  @XmlEnumValue("dz")
  DZ("dz"),
  @XmlEnumValue("ee")
  EE("ee"),
  @XmlEnumValue("el")
  EL("el"),
  @XmlEnumValue("en")
  EN("en"),
  @XmlEnumValue("eo")
  EO("eo"),
  @XmlEnumValue("es")
  ES("es"),
  @XmlEnumValue("et")
  ET("et"),
  @XmlEnumValue("eu")
  EU("eu"),
  @XmlEnumValue("fa")
  FA("fa"),
  @XmlEnumValue("ff")
  FF("ff"),
  @XmlEnumValue("fi")
  FI("fi"),
  @XmlEnumValue("fj")
  FJ("fj"),
  @XmlEnumValue("fo")
  FO("fo"),
  @XmlEnumValue("fr")
  FR("fr"),
  @XmlEnumValue("fy")
  FY("fy"),
  @XmlEnumValue("ga")
  GA("ga"),
  @XmlEnumValue("gd")
  GD("gd"),
  @XmlEnumValue("gl")
  GL("gl"),
  @XmlEnumValue("gn")
  GN("gn"),
  @XmlEnumValue("gu")
  GU("gu"),
  @XmlEnumValue("gv")
  GV("gv"),
  @XmlEnumValue("ha")
  HA("ha"),
  @XmlEnumValue("he")
  HE("he"),
  @XmlEnumValue("hi")
  HI("hi"),
  @XmlEnumValue("ho")
  HO("ho"),
  @XmlEnumValue("hr")
  HR("hr"),
  @XmlEnumValue("ht")
  HT("ht"),
  @XmlEnumValue("hu")
  HU("hu"),
  @XmlEnumValue("hy")
  HY("hy"),
  @XmlEnumValue("hz")
  HZ("hz"),
  @XmlEnumValue("ia")
  IA("ia"),
  @XmlEnumValue("id")
  ID("id"),
  @XmlEnumValue("ie")
  IE("ie"),
  @XmlEnumValue("ig")
  IG("ig"),
  @XmlEnumValue("ii")
  II("ii"),
  @XmlEnumValue("ik")
  IK("ik"),
  @XmlEnumValue("io")
  IO("io"),
  @XmlEnumValue("is")
  IS("is"),
  @XmlEnumValue("it")
  IT("it"),
  @XmlEnumValue("iu")
  IU("iu"),
  @XmlEnumValue("ja")
  JA("ja"),
  @XmlEnumValue("jv")
  JV("jv"),
  @XmlEnumValue("ka")
  KA("ka"),
  @XmlEnumValue("kg")
  KG("kg"),
  @XmlEnumValue("ki")
  KI("ki"),
  @XmlEnumValue("kj")
  KJ("kj"),
  @XmlEnumValue("kk")
  KK("kk"),
  @XmlEnumValue("kl")
  KL("kl"),
  @XmlEnumValue("km")
  KM("km"),
  @XmlEnumValue("kn")
  KN("kn"),
  @XmlEnumValue("ko")
  KO("ko"),
  @XmlEnumValue("kr")
  KR("kr"),
  @XmlEnumValue("ks")
  KS("ks"),
  @XmlEnumValue("ku")
  KU("ku"),
  @XmlEnumValue("kv")
  KV("kv"),
  @XmlEnumValue("kw")
  KW("kw"),
  @XmlEnumValue("ky")
  KY("ky"),
  @XmlEnumValue("la")
  LA("la"),
  @XmlEnumValue("lb")
  LB("lb"),
  @XmlEnumValue("lg")
  LG("lg"),
  @XmlEnumValue("li")
  LI("li"),
  @XmlEnumValue("ln")
  LN("ln"),
  @XmlEnumValue("lo")
  LO("lo"),
  @XmlEnumValue("lt")
  LT("lt"),
  @XmlEnumValue("lu")
  LU("lu"),
  @XmlEnumValue("lv")
  LV("lv"),
  @XmlEnumValue("mg")
  MG("mg"),
  @XmlEnumValue("mh")
  MH("mh"),
  @XmlEnumValue("mi")
  MI("mi"),
  @XmlEnumValue("mk")
  MK("mk"),
  @XmlEnumValue("ml")
  ML("ml"),
  @XmlEnumValue("mn")
  MN("mn"),
  @XmlEnumValue("mo")
  MO("mo"),
  @XmlEnumValue("mr")
  MR("mr"),
  @XmlEnumValue("ms")
  MS("ms"),
  @XmlEnumValue("mt")
  MT("mt"),
  @XmlEnumValue("my")
  MY("my"),
  @XmlEnumValue("na")
  NA("na"),
  @XmlEnumValue("nb")
  NB("nb"),
  @XmlEnumValue("nd")
  ND("nd"),
  @XmlEnumValue("ne")
  NE("ne"),
  @XmlEnumValue("ng")
  NG("ng"),
  @XmlEnumValue("nl")
  NL("nl"),
  @XmlEnumValue("nn")
  NN("nn"),
  @XmlEnumValue("no")
  NO("no"),
  @XmlEnumValue("nr")
  NR("nr"),
  @XmlEnumValue("nv")
  NV("nv"),
  @XmlEnumValue("ny")
  NY("ny"),
  @XmlEnumValue("oc")
  OC("oc"),
  @XmlEnumValue("oj")
  OJ("oj"),
  @XmlEnumValue("om")
  OM("om"),
  @XmlEnumValue("or")
  OR("or"),
  @XmlEnumValue("os")
  OS("os"),
  @XmlEnumValue("pa")
  PA("pa"),
  @XmlEnumValue("pi")
  PI("pi"),
  @XmlEnumValue("pl")
  PL("pl"),
  @XmlEnumValue("ps")
  PS("ps"),
  @XmlEnumValue("pt")
  PT("pt"),
  @XmlEnumValue("qu")
  QU("qu"),
  @XmlEnumValue("rm")
  RM("rm"),
  @XmlEnumValue("rn")
  RN("rn"),
  @XmlEnumValue("ro")
  RO("ro"),
  @XmlEnumValue("ru")
  RU("ru"),
  @XmlEnumValue("rw")
  RW("rw"),
  @XmlEnumValue("sa")
  SA("sa"),
  @XmlEnumValue("sc")
  SC("sc"),
  @XmlEnumValue("sd")
  SD("sd"),
  @XmlEnumValue("se")
  SE("se"),
  @XmlEnumValue("sg")
  SG("sg"),
  @XmlEnumValue("sh")
  SH("sh"),
  @XmlEnumValue("si")
  SI("si"),
  @XmlEnumValue("sk")
  SK("sk"),
  @XmlEnumValue("sl")
  SL("sl"),
  @XmlEnumValue("sm")
  SM("sm"),
  @XmlEnumValue("sn")
  SN("sn"),
  @XmlEnumValue("so")
  SO("so"),
  @XmlEnumValue("sq")
  SQ("sq"),
  @XmlEnumValue("sr")
  SR("sr"),
  @XmlEnumValue("ss")
  SS("ss"),
  @XmlEnumValue("st")
  ST("st"),
  @XmlEnumValue("su")
  SU("su"),
  @XmlEnumValue("sv")
  SV("sv"),
  @XmlEnumValue("sw")
  SW("sw"),
  @XmlEnumValue("ta")
  TA("ta"),
  @XmlEnumValue("te")
  TE("te"),
  @XmlEnumValue("tg")
  TG("tg"),
  @XmlEnumValue("th")
  TH("th"),
  @XmlEnumValue("ti")
  TI("ti"),
  @XmlEnumValue("tk")
  TK("tk"),
  @XmlEnumValue("tl")
  TL("tl"),
  @XmlEnumValue("tn")
  TN("tn"),
  @XmlEnumValue("to")
  TO("to"),
  @XmlEnumValue("tr")
  TR("tr"),
  @XmlEnumValue("ts")
  TS("ts"),
  @XmlEnumValue("tt")
  TT("tt"),
  @XmlEnumValue("tw")
  TW("tw"),
  @XmlEnumValue("ty")
  TY("ty"),
  @XmlEnumValue("ug")
  UG("ug"),
  @XmlEnumValue("uk")
  UK("uk"),
  @XmlEnumValue("ur")
  UR("ur"),
  @XmlEnumValue("uz")
  UZ("uz"),
  @XmlEnumValue("ve")
  VE("ve"),
  @XmlEnumValue("vi")
  VI("vi"),
  @XmlEnumValue("vo")
  VO("vo"),
  @XmlEnumValue("wa")
  WA("wa"),
  @XmlEnumValue("wo")
  WO("wo"),
  @XmlEnumValue("xh")
  XH("xh"),
  @XmlEnumValue("yi")
  YI("yi"),
  @XmlEnumValue("yo")
  YO("yo"),
  @XmlEnumValue("za")
  ZA("za"),
  @XmlEnumValue("zh")
  ZH("zh"),
  @XmlEnumValue("zu")
  ZU("zu");
  private final String value;

  ListLN(String v) {
    value = v;
  }

  public String value() {
    return value;
  }

  public static ListLN fromValue(String v) {
    for (ListLN c : ListLN.values()) {
      if (c.value.equals(v)) {
        return c;
      }
    }
    throw new IllegalArgumentException(v);
  }

}
