/* 
 * Copyright 2014 Key Bridge Global LLC.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package us.gov.dod.standard.ssrf._1_2_4.metadata.lists;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
import us.gov.dod.standard.ssrf._1_2_4.shared.ReleasableTo;

/**
 * Enumerated values for fields using the ListAN type.
 * <p>
 * Used in {@link ReleasableTo}
 * <p>
 * @author Jesse Caulfield
 * @version SSRF 1.2.4b, 11/12/2014
 */
@XmlType(name = "ListAN")
@XmlEnum
public enum ListAN {

  ABW("ABW"),
  AFG("AFG"),
  AFS("AFS"),
  AGL("AGL"),
  AIA("AIA"),
  ALB("ALB"),
  ALG("ALG"),
  AND("AND"),
  ARG("ARG"),
  ARM("ARM"),
  ARS("ARS"),
  ATA("ATA"),
  ATG("ATG"),
  AUS("AUS"),
  AUT("AUT"),
  AZE("AZE"),
  B("B"),
  BAH("BAH"),
  BDI("BDI"),
  BEL("BEL"),
  BEN("BEN"),
  BER("BER"),
  BFA("BFA"),
  BGD("BGD"),
  BHR("BHR"),
  BIH("BIH"),
  BIO("BIO"),
  BLR("BLR"),
  BLZ("BLZ"),
  BOL("BOL"),
  BOT("BOT"),
  BRB("BRB"),
  BRM("BRM"),
  BRU("BRU"),
  BTN("BTN"),
  BUL("BUL"),
  BVT("BVT"),
  CAF("CAF"),
  CAN("CAN"),
  CBG("CBG"),
  CHL("CHL"),
  CHN("CHN"),
  CHR("CHR"),
  CKH("CKH"),
  CLM("CLM"),
  CLN("CLN"),
  CME("CME"),
  COD("COD"),
  COG("COG"),
  COM("COM"),
  CPV("CPV"),
  CTI("CTI"),
  CTR("CTR"),
  CUB("CUB"),
  CVA("CVA"),
  CYM("CYM"),
  CYP("CYP"),
  CZE("CZE"),
  D("D"),
  DGA("DGA"),
  DJI("DJI"),
  DMA("DMA"),
  DNK("DNK"),
  DOM("DOM"),
  E("E"),
  EGY("EGY"),
  EQA("EQA"),
  ERI("ERI"),
  EST("EST"),
  ETH("ETH"),
  F("F"),
  FIN("FIN"),
  FJI("FJI"),
  FLK("FLK"),
  FRO("FRO"),
  FSM("FSM"),
  FYR("FYR"),
  G("G"),
  GAB("GAB"),
  GEO("GEO"),
  GHA("GHA"),
  GIB("GIB"),
  GMB("GMB"),
  GNB("GNB"),
  GNE("GNE"),
  GRC("GRC"),
  GRD("GRD"),
  GTM("GTM"),
  GUF("GUF"),
  GUI("GUI"),
  GUM("GUM"),
  GUY("GUY"),
  HKG("HKG"),
  HMD("HMD"),
  HND("HND"),
  HNG("HNG"),
  HOL("HOL"),
  HRV("HRV"),
  HTI("HTI"),
  I("I"),
  ICO("ICO"),
  IND("IND"),
  INS("INS"),
  IRL("IRL"),
  IRN("IRN"),
  IRQ("IRQ"),
  ISL("ISL"),
  ISR("ISR"),
  J("J"),
  JMC("JMC"),
  JOR("JOR"),
  KAZ("KAZ"),
  KEN("KEN"),
  KGZ("KGZ"),
  KIR("KIR"),
  KNA("KNA"),
  KOR("KOR"),
  KRE("KRE"),
  KWT("KWT"),
  LAO("LAO"),
  LBN("LBN"),
  LBR("LBR"),
  LBY("LBY"),
  LCA("LCA"),
  LIE("LIE"),
  LSO("LSO"),
  LTU("LTU"),
  LUX("LUX"),
  LVA("LVA"),
  MAC("MAC"),
  MAU("MAU"),
  MCO("MCO"),
  MDA("MDA"),
  MDG("MDG"),
  MEX("MEX"),
  MHL("MHL"),
  MLA("MLA"),
  MLD("MLD"),
  MLI("MLI"),
  MLT("MLT"),
  MNE("MNE"),
  MNG("MNG"),
  MOZ("MOZ"),
  MRC("MRC"),
  MSR("MSR"),
  MTN("MTN"),
  MWI("MWI"),
  NCG("NCG"),
  NCL("NCL"),
  NFK("NFK"),
  NGR("NGR"),
  NIG("NIG"),
  NIU("NIU"),
  NMB("NMB"),
  NOR("NOR"),
  NPL("NPL"),
  NRU("NRU"),
  NZL("NZL"),
  OMA("OMA"),
  PAK("PAK"),
  PHL("PHL"),
  PLW("PLW"),
  PNG("PNG"),
  PNR("PNR"),
  POL("POL"),
  POR("POR"),
  PRG("PRG"),
  PRU("PRU"),
  PSE("PSE"),
  PTC("PTC"),
  PTR("PTR"),
  QAT("QAT"),
  ROU("ROU"),
  RRW("RRW"),
  RUS("RUS"),
  S("S"),
  SDN("SDN"),
  SEN("SEN"),
  SEY("SEY"),
  SHN("SHN"),
  SLM("SLM"),
  SLV("SLV"),
  SMA("SMA"),
  SMO("SMO"),
  SMR("SMR"),
  SNG("SNG"),
  SOM("SOM"),
  SRB("SRB"),
  SRL("SRL"),
  STP("STP"),
  SUI("SUI"),
  SUR("SUR"),
  SVK("SVK"),
  SVN("SVN"),
  SWZ("SWZ"),
  SYR("SYR"),
  TCA("TCA"),
  TCD("TCD"),
  TGO("TGO"),
  THA("THA"),
  TJK("TJK"),
  TKL("TKL"),
  TKM("TKM"),
  TON("TON"),
  TRD("TRD"),
  TUN("TUN"),
  TUR("TUR"),
  TUV("TUV"),
  TZA("TZA"),
  UAE("UAE"),
  UGA("UGA"),
  UKR("UKR"),
  URG("URG"),
  USA("USA"),
  UZB("UZB"),
  VCT("VCT"),
  VEN("VEN"),
  VTN("VTN"),
  VUT("VUT"),
  WAK("WAK"),
  WAL("WAL"),
  YEM("YEM"),
  ZMB("ZMB"),
  ZWE("ZWE"),
  XSC("XSC"),
  XSU("XSU"),
  XUN("XUN"),
  XYU("XYU"),
  CCEB("CCEB"),
  NATO("NATO"),
  NEUR("NEUR"),
  XAEW("XAEW"),
  XASC("XASC"),
  XSFN("XSFN"),
  XHQ("XHQ"),
  XSMB("XSMB"),
  XO("XO"),
  XB("XB"),
  XL("XL"),
  XN("XN"),
  XT("XT"),
  @XmlEnumValue("XC3A")
  XC_3_A("XC3A"),
  XCSA("XCSA");
  private final String value;

  ListAN(String v) {
    value = v;
  }

  public String value() {
    return value;
  }

  public static ListAN fromValue(String v) {
    for (ListAN c : ListAN.values()) {
      if (c.value.equals(v)) {
        return c;
      }
    }
    throw new IllegalArgumentException(v);
  }

}
